# This is the configuration file for the [`taplo`][1] tool.  The tool can parse,
# check for well-formedness, validate against a schema, and format [`TOML`][2]
# files.
#
# [1]: https://crates.io/crates/taplo-cli
# [2]: https://toml.io/en/

[formatting]
align_comments = true
align_entries = false
allowed_blank_lines = 2
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true

# Setting the column width to '1' forces all arrays to be laid out vertically.
column_width = 1
compact_arrays = true
compact_entries = false
compact_inline_tables = false
crlf = false
indent_entries = false
indent_string = "    "
indent_tables = false
inline_table_expand = true
reorder_arrays = false
reorder_keys = false
trailing_newline = true
